# app/defaults.yaml

paths:
  exports_dir: "./exports"
  models_dir: "./models"
  data_dir: "./data"

audio:
  sample_rate: 44100
  fft_window_size: 2048
  hop_length: 512

onset_detection:
  threshold: 0.35
  smoothing: 0.5
  min_duration: 0.02

export:
  format: "csv"
  default_name: "analysis_result"
  include_headers: true

logging:
  debug: true
  log_file: "./logs/app.log"
  level: INFO

timing:
  enabled: true
  threshold_ms: 10